services:

  frontend:
    container_name: frontend
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:5173
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev-host